resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
  java_opts:
    - -XX:MaxRAMPercentage=65.0
    - -XX:+UseContainerSupport
    - --illegal-access=deny
    - --add-opens java.base/java.lang.invoke=ALL-UNNAMED