work_dir: "/opt/events"

application:
  name: events
  port:
    tcp:
      name: tcp
      number: 8000
    actuator:
      name: actuator
      number: 7000
  path:
    config: "{{ work_dir }}/config"
    logs: "{{ work_dir }}/logs"