---
- name: Create k8s config folder
  file:
    dest: "{{ path.k8s.directory.configs }}"
    state: directory

- name: Generate Kubernetes Configs from Templates
  template:
    src: "{{ path.k8s.directory.templates }}/{{ item }}.j2"
    dest: "{{ path.k8s.directory.configs }}/{{ item }}"
  with_items: "{{ path.k8s.files }}"

- name: Create Liquibase config folder
  file:
    dest: "{{ path.liquibase.directory.configs }}"
    state: directory
  when: env != 'local'

- name: Generate Liquibase Properties from Template
  template:
    src: "{{ path.liquibase.directory.templates }}/{{ item }}.j2"
    dest: "{{ path.liquibase.directory.configs }}/{{ item }}"
  with_items: "{{ path.liquibase.files }}"
  when: env != 'local'